#!/usr/bin/env bash
# Run on the HUB machine. Regenerates config/endpoints.yaml — the llm-d pool.
#
# Pool membership lives in config/pool.txt, one worker per line:
#   ip:port|device description
# e.g.
#   192.168.1.20:8001|Apple M3 Max · Metal
#   192.168.1.30:8001|NVIDIA RTX 5090 · WSL2
# Manage it with `./demo pool add|remove|list` (which calls this script), or
# edit it by hand and rerun this. The EPP watches the output file and
# live-reloads it — pool changes need no restarts.
#
# Compat: ENDPOINTS="ip:port ip:port" overrides pool.txt (no device labels).
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$REPO_DIR/config/endpoints.yaml"
POOL_FILE="${POOL_FILE:-$REPO_DIR/config/pool.txt}"
MODEL_LABEL="${MODEL_LABEL:-${SERVED_NAME:-llmd-demo}}"

# Build the candidate list: "ip:port|device" per line.
candidates=()
if [[ -n "${ENDPOINTS:-}" ]]; then
  for ep in $ENDPOINTS; do candidates+=("$ep|"); done
elif [[ -f "$POOL_FILE" ]]; then
  while IFS= read -r line; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    candidates+=("$line")
  done < "$POOL_FILE"
fi
[[ ${#candidates[@]} -gt 0 ]] || { echo "no pool members — add one with: ./demo pool add <ip:port> [\"device name\"]" >&2; exit 1; }

# A listed-but-dead endpoint WILL receive traffic (to the EPP it looks idle,
# which scores well under load) and requests to it fail. Keep the file matching
# reality: probe each endpoint and skip dead ones unless INCLUDE_DOWN=1.
live=()
for entry in "${candidates[@]}"; do
  ep="${entry%%|*}"; device="${entry#*|}"
  ip="${ep%:*}"; port="${ep##*:}"
  if ! [[ "$ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "skipping $ep — address must be a literal IPv4 (the file-discovery plugin does not resolve hostnames)" >&2
    continue
  fi
  # vLLM answers /health; other OpenAI-compatible engines answer / — accept either
  if [[ "${INCLUDE_DOWN:-0}" = "1" ]] || curl -sf -m 2 "http://$ep/health" >/dev/null 2>&1 \
      || curl -sf -m 2 "http://$ep/" >/dev/null 2>&1; then
    live+=("$entry")
  else
    echo "skipping $ep — not responding (start it, then rerun; the EPP live-reloads)" >&2
  fi
done
[[ ${#live[@]} -gt 0 ]] || { echo "no live endpoints found — refusing to write an empty pool" >&2; exit 1; }

{
  echo "# Generated by scripts/mac/gen-endpoints.sh — the entire \"cluster state\" of this demo."
  echo "# The EPP live-reloads this file (watchFile): edit it and routing follows."
  echo "endpoints:"
  # named by <last-octet>-<port> so an instance keeps its identity (and
  # dashboard color) as the pool grows and shrinks across machines
  for entry in "${live[@]}"; do
    ep="${entry%%|*}"; device="${entry#*|}"
    [[ "$device" == "$entry" ]] && device=""
    ip="${ep%:*}"; port="${ep##*:}"
    echo "  - name: vllm-${ip##*.}-$port"
    echo "    address: \"$ip\""
    echo "    port: \"$port\""
    echo "    labels:"
    echo "      model: $MODEL_LABEL"
    [[ -n "$device" ]] && echo "      llm-d.ai/device: \"$device\""
  done
} > "$OUT"

echo "wrote $OUT:"
sed 's/^/    /' "$OUT"
